version: 2
jobs:
  build:
    docker:
      - image: silex/emacs:25
    working_directory: ~/package+
    steps:
      - checkout
      - run: emacs --batch -Q -l tests.el -f ert-run-tests-batch-and-exit
